In [15]:
import numpy as np
from tensorflow.keras import models
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical

In [16]:
# Input data files are available in the "/kaggle/input/110-1-ntut-dl-app-hw1/" directory.
DATA_DIR = '/kaggle/input/ntutemnist/'
TRAIN_DATA_FILE = DATA_DIR + 'emnist-byclass-train.npz'
TEST_DATA_FILE = DATA_DIR + 'emnist-byclass-test.npz'

In [17]:
# Load training data
data = np.load(TRAIN_DATA_FILE)
train_labels = data['training_labels']
train_images = data['training_images']
train_labels

array([[35],
       [36],
       [ 6],
       ...,
       [ 5],
       [11],
       [22]], dtype=uint8)

In [18]:
trn_images = train_images.reshape((train_images.shape[0], 28 * 28))
trn_images = trn_images.astype('float32') / 255
trn_labels = to_categorical(train_labels)
trn_labels

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:
# Define Your Own Network
network = models.Sequential()
network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))
network.add(layers.Dense(128, activation='relu'))
network.add(layers.Dense(62, activation='softmax'))

# network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
network.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [20]:
network.fit(trn_images, trn_labels, epochs=20, batch_size=128)

Epoch 1/20
5453/5453 [==============================] - 51s 9ms/step - loss: 1.2821 - accuracy: 0.6396
Epoch 2/20
5453/5453 [==============================] - 48s 9ms/step - loss: 0.7313 - accuracy: 0.7733
Epoch 3/20
5453/5453 [==============================] - 49s 9ms/step - loss: 0.6088 - accuracy: 0.8033
Epoch 4/20
5453/5453 [==============================] - 49s 9ms/step - loss: 0.5515 - accuracy: 0.8175
Epoch 5/20
5453/5453 [==============================] - 50s 9ms/step - loss: 0.5165 - accuracy: 0.8266
Epoch 6/20
5453/5453 [==============================] - 51s 9ms/step - loss: 0.4939 - accuracy: 0.8321
Epoch 7/20
5453/5453 [==============================] - 52s 9ms/step - loss: 0.4761 - accuracy: 0.8362
Epoch 8/20
5453/5453 [==============================] - 51s 9ms/step - loss: 0.4628 - accuracy: 0.8400
Epoch 9/20
5453/5453 [==============================] - 53s 10ms/step - loss: 0.4519 - accuracy: 0.8427
Epoch 10/20
5453/5453 [==============================] - 52s 10ms/step -

In [21]:
# Evalute our model on test data
test_images = np.load(TEST_DATA_FILE)['testing_images']

In [22]:
tst_images = test_images.reshape((test_images.shape[0], 28 * 28))
tst_images = tst_images.astype('float32') / 255

In [23]:
# Print the predicted classes of test images
results = network.predict(tst_images).argmax(axis=-1)
results

3636/3636 [==============================] - 11s 3ms/step


array([ 1, 36,  0, ..., 55, 28, 24])

In [24]:
# Print results in CSV format and upload to Kaggle
with open('pred_results.csv', 'w') as f:
    f.write('Id,Category\n')
    for i in range(len(results)):
        f.write(str(i) + ',' + str(results[i]) + '\n')

In [25]:
# Download your results!
from IPython.display import FileLink
FileLink('pred_results.csv')

/kaggle/working/pred_results.csv